spring:
  application:
    name: prova3
  datasource:
    url: jdbc:mysql://localhost:3306/prova3
    username: webappuser
    password: webapppassword
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect